FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv

COPY pyproject.toml .

RUN uv sync

COPY . .

ENV HOST=api
ENV PORT=8000

CMD ["uv", "run", "python", "-m", "recovery.recovery"]