FROM python:3.12-slim

WORKDIR /app

# Install system deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl gcc \
    && rm -rf /var/lib/apt/lists/*

# Install uv
RUN pip install uv

# Copy dependency file
COPY pyproject.toml .

# Install dependencies
RUN uv sync

# Copy project
COPY . .

# Environment variables (connect to API container later)
ENV HOST=api
ENV PORT=8000

# Run worker
CMD ["uv", "run", "python", "-m", "workers.worker"]